import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";
import { Suspense } from "react";
import LoadingSpinner from "@/components/LoadingSpinner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Digital Market",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="h-full">
			<body
				className={cn("relative h-full font-sans antialiased", inter.className)}
			>
				<main className="relative flex flex-col min-h-screen">
					<Providers>
						<Suspense fallback={<LoadingSpinner />}>
							<Navbar />
							<div className="flex-grow flex-1">{children}</div>
						</Suspense>
					</Providers>
				</main>

				<Toaster position="top-center" richColors closeButton />
			</body>
		</html>
	);
}
